services:
  client-service:
    build:
      context: ../backend/client-service
      args:
        JAR_FILE: target/*.jar
    container_name: client-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://parking_db:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_APPLICATION_NAME: client-service
      JWT_SECRET: "your-secret-key-min-64-characters-long-for-production-use-only-12345"
      # OpenTelemetry configuration
      MANAGEMENT_TRACING_ENABLED: "true"
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://parking_otel_collector:4318/v1/traces
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
    networks:
      - parking-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

#  gate-control-service:
#    build:
#      context: ../backend/gate-control-service
#    container_name: gate-control-service
#    ports:
#      - "8082:8080"
#    depends_on:
#      - postgres
#      - eureka-server
#      - client-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      SPRING_APPLICATION_NAME: gate-control-service
#      CLIENT_SERVICE_URL: http://client-service:8080
#    networks:
#      - parking-network
#    restart: unless-stopped
#
#  billing-service:
#    build:
#      context: ../backend/billing-service
#    container_name: billing-service
#    ports:
#      - "8083:8080"
#    depends_on:
#      - postgres
#      - eureka-server
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      SPRING_APPLICATION_NAME: billing-service
#    networks:
#      - parking-network
#    restart: unless-stopped
#
#  management-service:
#    build:
#      context: ../backend/management-service
#    container_name: management-service
#    ports:
#      - "8084:8080"
#    depends_on:
#      - postgres
#      - eureka-server
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      SPRING_APPLICATION_NAME: management-service
#    networks:
#      - parking-network
#    restart: unless-stopped
#
#  reporting-service:
#    build:
#      context: ../backend/reporting-service
#    container_name: reporting-service
#    ports:
#      - "8085:8080"
#    depends_on:
#      - postgres
#      - eureka-server
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      SPRING_APPLICATION_NAME: reporting-service
#    networks:
#      - parking-network
#    restart: unless-stopped

  api-gateway:
    build:
      context: ../backend/api-gateway
    container_name: api-gateway
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://parking_db:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: parking_redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_APPLICATION_NAME: api-gateway
      JWT_SECRET: "your-secret-key-min-64-characters-long-for-production-use-only-12345"
      # OpenTelemetry configuration
      MANAGEMENT_TRACING_ENABLED: "true"
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://parking_otel_collector:4318/v1/traces
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
    networks:
      - parking-network
    restart: unless-stopped

networks:
  parking-network:
    name: devops_parking-network
    external: true
