version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: parking_db
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - parking_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d parking_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: parking_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  client-service:
    build:
      context: ../backend/client-service
      args:
        JAR_FILE: target/*.jar
    container_name: client-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  gate-control-service:
    build:
      context: ../backend/gate-control-service
    container_name: gate-control-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - client-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CLIENT_SERVICE_URL: http://client-service:8080

  billing-service:
    build:
      context: ../backend/billing-service
    container_name: billing-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  management-service:
    build:
      context: ../backend/management-service
    container_name: management-service
    ports:
      - "8084:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  reporting-service:
    build:
      context: ../backend/reporting-service
    container_name: reporting-service
    ports:
      - "8085:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  api-gateway:
    build:
      context: ../backend/api-gateway
    container_name: api-gateway
    ports:
      - "8086:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ""
      JWT_SECRET: "your-secret-key-min-64-characters-long-for-production-use-only-12345"

volumes:
  parking_data: {}