
services:
  postgres:
    networks:
      - app-network
    image: postgres:16-alpine
    container_name: parking_db
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - parking_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d parking_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client-service:
    networks:
      - app-network
    build:
      context: ./backend/client-service
      args:
        JAR_FILE: ./backend/client-service/target/*.jar
    container_name: client-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET:-ParkingSystemSecretKey2025!VeryLongAndSecureKey123456789}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  gate-control-service:
#    build:
#      context: ./backend/gate-control-service
#    container_name: gate-control-service
#    ports:
#      - "8082:8080"
#    depends_on:
#      - postgres
#      - client-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      CLIENT_SERVICE_URL: http://client-service:8080
#
#  billing-service:
#    build:
#      context: ./backend/billing-service
#    container_name: billing-service
#    ports:
#      - "8083:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#  management-service:
#    build:
#      context: ./backend/management-service
#    container_name: management-service
#    ports:
#      - "8084:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#  reporting-service:
#    build:
#      context: ./backend/reporting-service
#    container_name: reporting-service
#    ports:
#      - "8085:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
  eureka-server:
    image: steeltoeoss/eureka-server:latest
    container_name: eureka-server
    networks:
      - app-network
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false

  api-gateway:
    networks:
      - app-network
    build:
      context: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8086:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      JWT_SECRET: ${JWT_SECRET:-ParkingSystemSecretKey2025!VeryLongAndSecureKey123456789}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

networks:
  app-network:
    driver: bridge

volumes:
  parking_data: {}