spring:
  application:
    name: Client Service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/parking_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# JWT Configuration (must match API Gateway)
security:
  jwt:
    secret: ${JWT_SECRET:ParkingSystemSecretKey2025!VeryLongAndSecureKey123456789}

springdoc:
  swagger-ui:
    path: /swagger-ui.html # Path to interface
  api-docs:
    path: /v3/api-docs # Path to JSON-specification
  info:
    title: Parking Client Service API
    version: 1.0.0
    description: API to manage clients and vehicles

